### ISSUE TITLE
NON-CODING: Close issues in repo

### ISSUE THREAD

**Issue by brentonmdunn** [cse110-sp24-group14/cse110-sp24-group14#79]
For some reason, it looks like [issues](https://github.com/cse110-sp24-group14/cse110-sp24-group14/issues) aren't closing themselves when the PR is merged. All of the [closed PRs](https://github.com/cse110-sp24-group14/cse110-sp24-group14/pulls?q=is%3Apr+is%3Aclosed) should have a number attached to them. If they are closed but still display on the issues page, manually close the issue

Please message in Slack once you have completed this

**Comment by dylantrann** [comment]
Closed #64, #52, #48, and #25
